version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(ci-deps):"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps):"
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      commitlint:
        patterns:
          - "@commitlint/*"
