on: pull_request

name: Automerge
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  automerge:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "autorelease: pending"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "0"
          MERGE_RETRY_SLEEP: "0"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
          UPDATE_RETRIES: "0"
          UPDATE_RETRY_SLEEP: "0"
