on: push

name: CI / Create Release
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  build:
    if:  github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'main'
      - name: Set version
        run: |
          echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./main
      - name: Generate Changelog
        run: yarn auto-changelog --commit-limit false --starting-version {{env.VERSION}} -o VERSION.md --hide-credit
        working-directory: ./main
      - name: Read file
        id: changelog
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: './main/VERSION.md'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: false
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: './main/VERSION.md'
