on: push

name: CI / Create Release
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  publish-npm:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: "Publish to NPM"
    needs: [analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Create Release
    needs: [publish-npm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set version
        run: |
          echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - name: Generate Changelog
        run: npx auto-changelog --commit-limit 'false' --starting-version $TAG_VERSION -o 'VERSION.md' --hide-credit
      - name: Read file
        id: changelog
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: "./VERSION.md"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.TAG_VERSION }}
          body: ${{ steps.changelog.outputs.content }}
          draft: false
          prerelease: false
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./VERSION.md"

  changelog:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Update main changelog
    needs: [publish-npm]
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run auto-changelog
        run: npx auto-changelog --commit-limit 'false' --hide-credit
      - name: Commit and push Changelog
        # if: endsWith(github.ref, 'patch') != true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am ":notebook: Update changelog" || echo "No changes to commit"
          git push || echo "Nothing to push"
      # - name: Commit and co Changelog
      #   if: endsWith(github.ref, 'patch')
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -am ":notebook: Update changelog" || echo "No changes to commit"
      #     git push || echo "Nothing to push"
      #     git push --set-upstream origin patch/update-changelog
