on:
  push:
    branches:
      - main
      - 'release-*'

name: CI
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release') || github.ref == 'refs/heads/main'"
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
