on:
  push:
    branches:
      - main

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: lokalise-to-default-messages
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"build(deps)","section":"Dependencies","hidden":false},{"type":"docs","section":"Documentation","hidden":false}]'

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup node
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
