on:
  release:
    types: [created]

name: Release
jobs:
  publish-npm:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
