on:
  push:
    branches:
      - main

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release please
        id: release
        uses: google-github-actions/release-please-action@v4

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm pkg delete scripts.prepare && npm publish --omit=dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
